# Generated by Django 6.1.2 on 2026-10-06 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissionsUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionuser',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='permissionuser',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='uq_permission_user'),
        ),
    ]
